creates rgs and outputs, commented prod related workflow parts out

diff --git a/.github/workflows/backend-plan-deploy.yml b/.github/workflows/backend-plan-deploy.yml
--- a/.github/workflows/backend-plan-deploy.yml
+++ b/.github/workflows/backend-plan-deploy.yml
@@ -62,71 +62,71 @@ jobs:
           if [ $exitcode -eq 1 ]; then
             echo Terraform Plan Failed!
             exit 1
-          else 
+          else
             exit 0
           fi
           
-      # Save plan to artifacts  
+      # Save plan to artifacts
       - name: Publish Terraform Plan
         uses: actions/upload-artifact@v4
         with:
           name: tfplan_nonprod
           path: remote_state_backend/nonprod/tfplan_nonprod
 
-  terraform-plan-prod:
-    name: 'Terraform Plan Prod'
-    runs-on: ubuntu-latest
-    env:
-      #this is needed since we are running terraform with read-only permissions
-      ARM_SKIP_PROVIDER_REGISTRATION: true
-    outputs:
-      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
+  #terraform-plan-prod:
+  #  name: 'Terraform Plan Prod'
+  #  runs-on: ubuntu-latest
+  #  env:
+  #    #this is needed since we are running terraform with read-only permissions
+  #    ARM_SKIP_PROVIDER_REGISTRATION: true
+  #  outputs:
+  #    tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
 
-    steps:
-      # Checkout the repository to the GitHub Actions runner
-      - name: Check out repository
-        uses: actions/checkout@v4
+  #  steps:
+  #    # Checkout the repository to the GitHub Actions runner
+  #    - name: Check out repository
+  #      uses: actions/checkout@v4
 
-      # Install the latest version of the Terraform CLI
-      - uses: hashicorp/setup-terraform@v3
-        with:
-          terraform_version: 1.8.1
-          terraform_wrapper: false
+  #    # Install the latest version of the Terraform CLI
+  #    - uses: hashicorp/setup-terraform@v3
+  #      with:
+  #        terraform_version: 1.8.1
+  #        terraform_wrapper: false
 
-      # Initialize a new or existing Terraform working directory by creating initial files,
-      # loading any remote state, downloading modules, etc.
-      - name: Terraform Init
-        working-directory: ./remote_state_backend/prod
-        run: terraform init
+  #    # Initialize a new or existing Terraform working directory by creating initial files,
+  #    # loading any remote state, downloading modules, etc.
+  #    - name: Terraform Init
+  #      working-directory: ./remote_state_backend/prod
+  #      run: terraform init
 
-      # Checks that all Terraform configuration files adhere to a canonical format
-      # Will fail the build if not
-      - name: Terraform Format
-        working-directory: ./remote_state_backend/prod
-        run: terraform fmt -check
+  #    # Checks that all Terraform configuration files adhere to a canonical format
+  #    # Will fail the build if not
+  #    - name: Terraform Format
+  #      working-directory: ./remote_state_backend/prod
+  #      run: terraform fmt -check
 
-      # Generates an execution plan for Terraform
-      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
-      - name: Terraform Plan
-        working-directory: ./remote_state_backend/prod
-        id: tf-plan
-        run: |
-          export exitcode=0
-          terraform plan -detailed-exitcode -no-color -out tfplan_prod || export exitcode=$?
-          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
-          if [ $exitcode -eq 1 ]; then
-            echo Terraform Plan Failed!
-            exit 1
-          else 
-            exit 0
-          fi
+  #    # Generates an execution plan for Terraform
+  #    # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+  #    - name: Terraform Plan
+  #      working-directory: ./remote_state_backend/prod
+  #      id: tf-plan
+  #      run: |
+  #        export exitcode=0
+  #        terraform plan -detailed-exitcode -no-color -out tfplan_prod || export exitcode=$?
+  #        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+  #        if [ $exitcode -eq 1 ]; then
+  #          echo Terraform Plan Failed!
+  #          exit 1
+  #        else
+  #          exit 0
+  #        fi
 
-      # Save plan to artifacts  
-      - name: Publish Terraform Plan
-        uses: actions/upload-artifact@v4
-        with:
-          name: tfplan_prod
-          path: remote_state_backend/prod/tfplan_prod
+  #    # Save plan to artifacts
+  #    - name: Publish Terraform Plan
+  #      uses: actions/upload-artifact@v4
+  #      with:
+  #        name: tfplan_prod
+  #        path: remote_state_backend/prod/tfplan_prod
 
   terraform-apply-nonprod:
     name: 'Terraform Apply NonProd'
@@ -163,38 +163,38 @@ jobs:
       run: terraform apply -input=false -no-color -auto-approve tfplan_nonprod
       working-directory: ./remote_state_backend/nonprod
 
-  terraform-apply-prod:
-    name: 'Terraform Apply Prod'
-    runs-on: ubuntu-latest
-    environment: prod
-    needs: [terraform-plan-prod]
+  #terraform-apply-prod:
+  #  name: 'Terraform Apply Prod'
+  #  runs-on: ubuntu-latest
+  #  environment: prod
+  #  needs: [terraform-plan-prod]
 
-    steps:
-    # Checkout the repository to the GitHub Actions runner
-    - name: Checkout
-      uses: actions/checkout@v4
+  #  steps:
+  #  # Checkout the repository to the GitHub Actions runner
+  #  - name: Checkout
+  #    uses: actions/checkout@v4
 
-    # Install the latest version of Terraform CLI
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v3
-      with:
-        terraform_version: 1.8.1
-        terraform_wrapper: false
+  #  # Install the latest version of Terraform CLI
+  #  - name: Setup Terraform
+  #    uses: hashicorp/setup-terraform@v3
+  #    with:
+  #      terraform_version: 1.8.1
+  #      terraform_wrapper: false
 
-    # Initialize a new or existing Terraform working directory by creating initial files,
-    # loading any remote state, downloading modules, etc.
-    - name: Terraform Init
-      run: terraform init
-      working-directory: ./remote_state_backend/prod
+  #  # Initialize a new or existing Terraform working directory by creating initial files,
+  #  # loading any remote state, downloading modules, etc.
+  #  - name: Terraform Init
+  #    run: terraform init
+  #    working-directory: ./remote_state_backend/prod
 
-    # Download saved plan from artifacts
-    - name: Download Terraform Plan
-      uses: actions/download-artifact@v4
-      with:
-        name: tfplan_prod
-        path: remote_state_backend/prod/
+  #  # Download saved plan from artifacts
+  #  - name: Download Terraform Plan
+  #    uses: actions/download-artifact@v4
+  #    with:
+  #      name: tfplan_prod
+  #      path: remote_state_backend/prod/
 
-    # Terraform Apply
-    - name: Terraform Apply
-      run: terraform apply -input=false -no-color -auto-approve tfplan_prod
-      working-directory: ./remote_state_backend/prod
+  #  # Terraform Apply
+  #  - name: Terraform Apply
+  #    run: terraform apply -input=false -no-color -auto-approve tfplan_prod
+  #    working-directory: ./remote_state_backend/prod
